#!/bin/bash

git clone https://github.com/mrirecon/bart.git
cd bart
make
cd ..

python -m pip install bash_kernel
python -m bash_kernel.install

python -m pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user

python -m pip install jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user

jupyter nbextensions enable collapsible_headings/main
jupyter nbextensions enable toc2/main

cd bart
. startup.sh
cd ..
