#!/bin/bash

git clone https://github.com/mrirecon/bart.git
cd bart
make
. startup.sh
cd ..

pip install bash_kernel
python -m bash_kernel.install

pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user

pip install jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user
